Create binaries on each release
rivosinc/prometheus-slurm-exporter pull request #92
Opened 2024-08-14 09:57 UTC by willfurnell

This pull request adds functionality, using 'goreleaser', to build binaries on each release.

2024-08-14 22:05 UTC, abhinavDhulipala commented on .github/workflows/release.yml
> +        uses: actions/setup-go@v5
Please add the following:

```yml
      with:
        go-version: '>=1.20'
```

2024-08-14 22:07 UTC, abhinavDhulipala requested changes

2024-08-14 22:07 UTC, abhinavDhulipala commented on .github/workflows/release.yml
> +name: goreleaser
To pass reuse, we must add the following header to the top of the file:

```yml
# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0
```

2024-08-14 22:18 UTC, abhinavDhulipala commented
We might also want to consider making this action dependent on the testing stage of our pipeline. All though it could also be argued that it is safe to assume the code at the tag would be working, I would still put the clause in just to be sure. Our pre-commit and tests are fast anyway.

2024-08-15 10:19 UTC, willfurnell commented
Annoyingly making it dependent on the testing stage of the pipeline looks difficult - because you _can_ do it, but then it will run every time the verify/testing action runs - and we don't want to be building binaries for every commit, I think? https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run
Up to you though as it's your project! :)

2024-08-15 22:38 UTC, abhinavDhulipala commented
This is awesome! Thanks a ton. I'll merge this in and give it a try.

2024-08-15 22:41 UTC, abhinavDhulipala approved these changes
Looks great! I'll create a new micro release in the next couple days to test this out.

2024-08-15 22:41 UTC, merged