Feature: Distribution Packages
rivosinc/prometheus-slurm-exporter pull request #97
Opened 2024-08-28 12:02 UTC by drewstinnett

This PR adds RPM and Deb packaging from goreleaser, as well as a little systemd file to start and stop the service.

2024-08-28 12:04 UTC, drewstinnett commented
Oops, need to fix reuse workflow..

2024-08-28 17:24 UTC, NucciTheBoss commented
Hah, looks like we had the same idea this week (#96) - this is great! :laughing: 

I published a [PPA for Noble and Jammy on Launchpad](https://launchpad.net/~ubuntu-hpc/+archive/ubuntu/prometheus-slurm-exporter) for the exporter. I've reached out to the Debian Go team about getting the exporter uploaded to Debian. It would be great to have latest builds published to GitHub and a `git buildpackage` version on Salsa for inclusion into Debian :smile:

2024-08-28 17:29 UTC, drewstinnett commented
> Hah, looks like we had the same idea this week (#96) - this is great! 😆
> 
> I published a [PPA for Noble and Jammy on Launchpad](https://launchpad.net/~ubuntu-hpc/+archive/ubuntu/prometheus-slurm-exporter) for the exporter. I've reached out to the Debian Go team about getting the exporter uploaded to Debian. It would be great to have latest builds published to GitHub and a `git buildpackage` version on Salsa for inclusion into Debian 😄

Oh I totally missed that...good timing!!

2024-08-28 19:58 UTC, abhinavDhulipala commented
Howdy! First of all thanks a ton for your contributions. Give me a day or 2 wrap my mind around this MR and get back to you. In the meanwhile, I don't _think_ tracing functionality is supported the way it is packaged right now. Please checkout my latest MR #95 for how to package and resolve the html files to support tracing. In short, we need to package the `./exporter/templates/*` html files. In the systemd file and pkgs, we need to support pointing to the proper templated directory using the [TRACE_ROOT_PATH](https://github.com/rivosinc/prometheus-slurm-exporter?tab=readme-ov-file#exporter-env-var-docs) env var.

2024-08-28 20:07 UTC, drewstinnett commented
Ah yes that makes sense I'll add that in shortly... Thank you!

2024-08-29 13:42 UTC, drewstinnett commented
Ok @abhinavDhulipala, I think the packaging is correct now if you'd like to take a look when you can (No rush here btw, and thank you so much for this awesome project! 🙏)

Just a thought, but how would you feel if I changed the TRACE_ROOT_PATH logic in the code to look in the order:

1. $TRACE_ROOT_PATH path
2. . (cwd)
3. /usr/share/prometheus-slurm-exporter/templates/

I don't think that would break any current workflows, but it would allow users of the distro packages to use tracing without having to specify an additional env variable. If that is something you would be interested in, I'd be happy to make that change as well as part of this PR. No worries if you'd like to keep it the same though too.

Thank you again!

2024-09-02 02:50 UTC, abhinavDhulipala commented
Howdy @drewstinnett that trace path feature looks like a great feature, but we could also configure the environment variable of the systemd file to fill in the $TRACE_PATH to `/usr/share/prometheus-slurm-exporter/templates`. If we were to implement the scheme above, I think we should implement it in the following way:

1. If `TRACE_ROOT_PATH` is specified, search that directory. If we don't find a `templates` dir, let's panic and crash the program.
2. If `TRACE_ROOT_PATH` **isn't** specified, we can search cwd and /usr/share/prometheus-slurm-exporter. 


Now, I tried to install debian found on your forks release [page](https://github.com/drewstinnett/prometheus-slurm-exporter/releases/tag/v0.0.3). I did the following in case you want to repro:

```bash
docker run -ti --rm --platform linux/amd64 ubuntu:22.04 bash
$ apt update -y && apt-get install wget -y && mkdir /workspace
$ cd /workspace
$ wget https://github.com/drewstinnett/prometheus-slurm-exporter/releases/download/v0.0.3/prometheus-slurm-exporter_0.0.3_linux_amd64.deb
$  apt-get install -f prometheus-slurm-exporter_0.0.3_linux_amd64.deb
# unfortunately got the following
$  stat /usr/share/prometheus-slurm-exporter/         
stat: cannot statx '/usr/share/prometheus-slurm-exporter/': No such file or directory
```

It doesn't look like the templates were packaged. Is this stale perhaps? Also, could you rebase as well :)

Thanks again for all your hard work!

2024-09-03 12:03 UTC, drewstinnett commented
Thank you @abhinavDhulipala, I will work on these fixes/changes!

2024-09-03 14:46 UTC, drewstinnett commented
Working on the trace logic...quick question for you @abhinavDhulipala, should the app do a 'deep' search of the TRACE_ROOT_PATH for the 'templates' directory, or do we always expect it to be right under the top path? For example:

if TRACE_ROOT_PATH is set to "/srv", should "/srv/subdir/templates" be considered valid, or would we only want to look at "/srv/templates"? Either is fine with me, just wanted to check the intended behavior. Thank you!

2024-09-03 15:02 UTC, abhinavDhulipala commented
I have it now as a recursive search, but I think that could be a potential bottleneck if configured wrong. Let's modify it to simply checking for the existence of the one html file we have now.

2024-09-03 20:04 UTC, drewstinnett commented
Ok, whenever you get a chance, can you give it another review? I think I was mis-using the github-release command, which appears to have generated the packages based off of an older tag. I think this is fixed now. I verified with:

```bash
$ goreleaser release --clean --snapshot
...
$ dpkg-deb -c dist/prometheus-slurm-exporter_1.6.5-SNAPSHOT-0969bb7_linux_amd64.deb
drwxr-xr-x root/root         0 2024-09-03 10:02 ./usr/
drwxr-xr-x root/root         0 2024-09-03 10:02 ./usr/bin/
-rwxr-xr-x root/root  10014872 2024-09-03 10:02 ./usr/bin/prometheus-slurm-exporter
drwxr-xr-x root/root         0 2024-09-03 10:02 ./usr/lib/
drwxr-xr-x root/root         0 2024-09-03 10:02 ./usr/lib/systemd/
drwxr-xr-x root/root         0 2024-09-03 10:02 ./usr/lib/systemd/system/
-rw-r--r-- root/root       250 2024-09-03 09:35 ./usr/lib/systemd/system/prometheus-slurm-exporter.service
drwxr-xr-x root/root         0 2024-09-03 10:02 ./usr/share/
drwxr-xr-x root/root         0 2024-09-03 10:02 ./usr/share/prometheus-slurm-exporter/
drwxr-xr-x root/root         0 2024-09-03 10:02 ./usr/share/prometheus-slurm-exporter/templates/
-rw-r--r-- root/root       927 2024-08-27 10:47 ./usr/share/prometheus-slurm-exporter/templates/proc_traces.html
```

The logic for the detection is also in place now

```bash
$ LOGLEVEL=debug prometheus-slurm-exporter -trace.enabled=true
time=2024-09-03T12:22:40.135-04:00 level=INFO msg="trace path enabled at path: :9092/trace"
time=2024-09-03T12:22:40.136-04:00 level=DEBUG msg="using trace template path: /usr/share/prometheus-slurm-exporter/templates"
time=2024-09-03T12:22:40.136-04:00 level=INFO msg="serving metrics at :9092/metrics"
…
$ LOGLEVEL=debug TRACE_ROOT_PATH=/tmp/empty-dir prometheus-slurm-exporter -trace.enabled=true
time=2024-09-03T12:23:46.371-04:00 level=INFO msg="trace path enabled at path: :9092/trace"
panic: TRACE_ROOT_PATH must include a directory called: templates
…
```

Happy to make whatever tweaks/changes you suggest in addition to these as well. Thank you!

2024-09-06 07:08 UTC, abhinavDhulipala requested changes
The biggest takeaway here is that I've found it cumbersome to install this in containers which I often use for deployment. Let me know what you think!

2024-09-06 07:08 UTC, abhinavDhulipala commented on .goreleaser.yaml
> +    maintainer: abhinavDhulipal
:)

```suggestion
    maintainer: abhinavDhulipala
```

2024-09-06 07:08 UTC, abhinavDhulipala commented on packaging/postinstall.sh
> +systemctl enable --now prometheus-slurm-exporter.service
I'm conflicted on whether we should install a systemctl function by default. I personally won't be using this method of deployment and when I try to develop and test out of containers this gets in the way quite a bit. I'd suggest remove this entirely. We could guard with the following: `[[ -d /run/systemd/system ]] && ...`, but I still would prefer to drop this and just put this as documentation. Perhaps a curlable snippet of some kind.

2024-09-06 07:08 UTC, abhinavDhulipala commented on exporter/trace_test.go
> +}
This is an awesome test! Great work.

2024-09-06 15:36 UTC, drewstinnett commented on packaging/postinstall.sh
> +systemctl enable --now prometheus-slurm-exporter.service
I understand what you mean...I'll make this update removing the systemd components from the packaging and include a snippet in the documentation that can be copy/pasted. Thank you for that feedback!

2024-09-09 14:43 UTC, drewstinnett commented on packaging/postinstall.sh
> +systemctl enable --now prometheus-slurm-exporter.service
Ok, systemd bits have been removed from the packaging, and I added a little copy/pastable snippet to the README for folks that would like to enable it as a systemd service. Look ok? Thank you!

2024-09-10 17:52 UTC, abhinavDhulipala approved these changes
This looks awesome, thanks a ton for all your hard work once again.

2024-09-10 17:53 UTC, merged